sudo: required

env:
  - NPM_TARGET=lint
  - NPM_TARGET=test
  - NPM_TARGET=coverage

language: node_js

node_js:
  - "8.3"

services:
  - docker

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot_hello .

script:
  - docker run --rm probot_hello npm run $NPM_TARGET
  - ls

after_success:
  - echo "We were successful!!!"
  - node success.js